pipeline {
    agent any

    environment {
        REGISTRY = 'ghcr.io/saipappala'
        SERVICE_DIR = 'student-service' // Change to 'studylog-service' for the second pipeline
        IMAGE_NAME = "${SERVICE_DIR}"
        TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile & Test') {
            steps {
                // Change directory to the service folder before running Maven
                dir("${SERVICE_DIR}") {
                //    sh './mvnw clean test'
                sh '''
                # Locate Java binary and find its true JDK home
                export JAVA_HOME=$(readlink -f $(which java) | sed "s:/bin/java::")
                echo "Detected JAVA_HOME: $JAVA_HOME"
                export PATH=$JAVA_HOME/bin:$PATH
                
                ./mvnw clean test
            '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                // Point docker build directly to the Dockerfile and context path inside the service folder
                sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${TAG} -t ${REGISTRY}/${IMAGE_NAME}:latest ./${SERVICE_DIR}"
            }
        }

        stage('Push Image to Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-container-registry-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh "echo ${PASS} | docker login ghcr.io -u ${USER} --password-stdin"
                    sh "docker push ${REGISTRY}/${IMAGE_NAME}:${TAG}"
                    sh "docker push ${REGISTRY}/${IMAGE_NAME}:latest"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
