apiVersion: apps/v1
kind: Deployment
metadata:
  name: studylog-service
  labels:
    app: studylog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studylog-service
  template:
    metadata:
      labels:
        app: studylog-service
    spec:
      containers:
        - name: studylog-service
          image: ghcr.io/saipappala/studylog-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-db-secret
                  key: DB_PASSWORD
